---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Author
- type: document
  path: data/en/author.yaml
  label: Author (EN)
- type: document
  path: data/de/author.yaml
  label: Author (DE)
- type: heading
  label: Site
- type: document
  path: data/en/site.yaml
  label: Site Details (EN)
- type: document
  path: data/de/site.yaml
  label: Site Details (DE)
- type: heading
  label: Sections
- type: directory
  path: data/de/sections/*
  label: Section - German
  create: all
  match: "**/*"
  new_doc_ext: ".yaml"
- type: directory
  path: data/en/sections/*
  label: Sections - English
  create: all
  match: "**/*"
  new_doc_ext: ".yaml"
- type: heading
  label: Blog
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: heading
  label: Notes
- type: directory
  path: content/notes
  label: Notes
  create: all
  match: "**/*"
upload_dir: assets/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
